//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJudge.Service.CodeExecutionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodeExecutionService.ICodeExecutionService")]
    public interface ICodeExecutionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeExecutionService/Compile", ReplyAction="http://tempuri.org/ICodeExecutionService/CompileResponse")]
        bool Compile(string codeFilePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeExecutionService/Compile", ReplyAction="http://tempuri.org/ICodeExecutionService/CompileResponse")]
        System.Threading.Tasks.Task<bool> CompileAsync(string codeFilePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeExecutionService/Run", ReplyAction="http://tempuri.org/ICodeExecutionService/RunResponse")]
        bool Run(string codeFilePath, string[] commandLineParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeExecutionService/Run", ReplyAction="http://tempuri.org/ICodeExecutionService/RunResponse")]
        System.Threading.Tasks.Task<bool> RunAsync(string codeFilePath, string[] commandLineParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeExecutionServiceChannel : OnlineJudge.Service.CodeExecutionService.ICodeExecutionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeExecutionServiceClient : System.ServiceModel.ClientBase<OnlineJudge.Service.CodeExecutionService.ICodeExecutionService>, OnlineJudge.Service.CodeExecutionService.ICodeExecutionService {
        
        public CodeExecutionServiceClient() {
        }
        
        public CodeExecutionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeExecutionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeExecutionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeExecutionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Compile(string codeFilePath) {
            return base.Channel.Compile(codeFilePath);
        }
        
        public System.Threading.Tasks.Task<bool> CompileAsync(string codeFilePath) {
            return base.Channel.CompileAsync(codeFilePath);
        }
        
        public bool Run(string codeFilePath, string[] commandLineParameters) {
            return base.Channel.Run(codeFilePath, commandLineParameters);
        }
        
        public System.Threading.Tasks.Task<bool> RunAsync(string codeFilePath, string[] commandLineParameters) {
            return base.Channel.RunAsync(codeFilePath, commandLineParameters);
        }
    }
}
